labels = {
    "_adisk._tcp.local.": "Apple Time Machine Disk",
    "_afpovertcp._tcp.local.": "AFP over TCP (Apple File Sharing)",
    "_airdrop._tcp.local.": "Apple AirDrop",
    "_airplay._tcp.local.": "AirPlay",
    "_apple-mobdev._tcp.local.": "Apple Mobile Device",
    "_axis-video._tcp.local.": "Axis Network Camera",
    "_chromecast._tcp.local.": "Google Chromecast",
    "_companion-link._tcp.local.": "Apple Device Companion Link",
    "_daap._tcp.local.": "Digital Audio Access Protocol (iTunes Music Sharing)",
    "_dacp._tcp.local.": "iTunes Remote Control (DACP)",
    "_device-info._tcp.local.": "Device Info",
    "_eero._tcp.local.": "Eero Wi-Fi Mesh",
    "_eppc._tcp.local.": "Apple Events/Remote AppleScript",
    "_face-time._tcp.local.": "Apple FaceTime",
    "_ftp._tcp.local.": "FTP",
    "_googlecast._tcp.local.": "Google Cast",
    "_hap._tcp.local.": "HomeKit Accessory Protocol",
    "_hkp._tcp.local.": "HKP (OpenPGP Keyserver)",
    "_homekit._tcp.local.": "Apple HomeKit",
    "_http._tcp.local.": "HTTP",
    "_hue._tcp.local.": "Philips Hue Bridge",
    "_ipp-everywhere._tcp.local.": "IPP Everywhere Printer",
    "_ipp-usb._tcp.local.": "USB-over-IPP Printer",
    "_ipp._tcp.local.": "Internet Printing Protocol",
    "_ipps._tcp.local.": "IPP over TLS (Secure IPP Printing)",
    "_meshcop._udp.local.": "Thread Mesh Network Commissioning",
    "_mqtt._tcp.local.": "MQTT Broker",
    "_net-assistant._udp.local.": "Network Assistant",
    "_nfs._tcp.local.": "NFS (Network File System)",
    "_odproxy._tcp.local.": "Open Directory Proxy",
    "_parentcontrol._tcp.local.": "Parental Controls",
    "_printer._tcp.local.": "Printer",
    "_raop._tcp.local.": "Remote Audio Output Protocol (AirPlay Audio)",
    "_rdlink._tcp.local.": "Remote Desktop Link",
    "_rfb._tcp.local.": "VNC Remote Framebuffer",
    "_scanner._tcp.local.": "Scanner",
    "_sftp-ssh._tcp.local.": "SFTP over SSH",
    "_sleep-proxy._udp.local.": "Sleep Proxy",
    "_smb._tcp.local.": "SMB (Windows File Sharing)",
    "_spotify-connect._tcp.local.": "Spotify Connect",
    "_srpl-tls._tcp.local.": "Secure Remote Password over TLS",
    "_ssh._tcp.local.": "SSH (Secure Shell)",
    "_tivo-mind._tcp.local.": "TiVo Media Server",
    "_touch-able._tcp.local.": "Apple Touch",
    "_trel._udp.local.": "Thread Network",
    "_udp.local.": "UDP Service",
    "_vnc._tcp.local.": "VNC",
    "_workstation._tcp.local.": "Workstation",
    "_xbmc-jsonrpc-h._tcp.local.": "Kodi (XBMC) Media Center",
    # Add more as you discover them!
}